# Generated by Django 5.1.1 on 2024-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportsmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('spcat', models.CharField(max_length=100)),
                ('sptype', models.CharField(max_length=100)),
            ],
        ),
    ]
