# Generated by Django 5.1.1 on 2024-11-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_4', '0002_sportsmen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sportsmen',
            new_name='Sportspeople',
        ),
    ]
