# Generated by Django 5.1.1 on 2024-11-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_4', '0003_rename_sportsmen_sportspeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportspeople',
            name='sptype',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='sportspeople',
            unique_together={('name', 'surname', 'age', 'gender', 'spcat', 'sptype')},
        ),
    ]
